import fs from "node:fs"; import path from "node:path"; import { describe,expect,it } from "vitest";
import { initSqlite } from "../src/main/db/sqlite"; import { createLocalRepositories } from "../src/main/adapters/local-repositories";
import { JobIndexService } from "../src/main/job-index/job-index.service"; import { createOfferFingerprint,normalizeOfferUrl } from "../src/main/job-index/fingerprint";
import { findDuplicate } from "../src/main/job-index/deduplication.service"; import { mapPracujListing } from "../src/main/collectors/portals/pracuj.mapper"; import { pracujRawListing } from "./fixtures/pracuj-listing";
const withDb=async(fn:(x:ReturnType<typeof initSqlite>,r:ReturnType<typeof createLocalRepositories>)=>Promise<void>)=>{const file=path.resolve(process.cwd(),"data",`job-index-${Date.now()}-${Math.random()}.db`);const ctx=initSqlite(file);try{await fn(ctx,createLocalRepositories(ctx));}finally{ctx.sqlite.close();fs.rmSync(file,{force:true});}};
const service=(offers:ReturnType<typeof createLocalRepositories>["offers"])=>new JobIndexService(offers,{start:async()=>({runId:"x"})} as never,{recheck:async()=>({checked:0,active:0,expired:0,unavailable:0,redirected:0,unknown:0,errors:0})} as never,{info:()=>undefined} as never);

describe("Job Index",()=>{
 it("normalizes URLs and maps raw portal data without Playwright",()=>{expect(normalizeOfferUrl("https://x.test/job/1?utm_source=a#x")).toBe("https://x.test/job/1");expect(mapPracujListing(pracujRawListing)?.title).toBe("Senior React Developer");});
 it("deduplicates by fingerprint after sourceId and URL",async()=>withDb(async(_ctx,r)=>{const a=await r.offers.create({source:"pracuj",url:"https://x.test/a",title:"React Dev",company:"Acme",location:"Warsaw"});expect(findDuplicate({source:"other",sourceId:null,url:"https://different.test/x",title:" react dev ",company:"ACME",location:"Warsaw"},[a])?.id).toBe(a.id);const b=await r.offers.upsert({source:"other",url:"https://different.test/x",title:"React Dev",company:"Acme",location:"Warsaw"});expect(b.created).toBe(false);}));
 it("preserves user status and records meaningful changes",async()=>withDb(async(ctx,r)=>{const a=await r.offers.create({source:"pracuj",sourceId:"1",url:"https://x.test/1",title:"Old",company:"Acme",location:"Warsaw",status:"saved"});const b=await r.offers.upsert({source:"pracuj",sourceId:"1",url:"https://x.test/1",title:"New"});expect(b.offer.status).toBe("saved");expect(b.offer.lastSeenAt>=a.lastSeenAt).toBe(true);expect((ctx.sqlite.prepare("select count(*) count from offer_changes where offer_id=?").get(a.id) as {count:number}).count).toBe(1);}));
 it("reindexes, merges duplicates, validates incomplete records",async()=>withDb(async(_ctx,r)=>{await r.offers.create({source:"pracuj",url:"https://x.test/1?ref=a",title:"React Dev",company:"Acme",location:"Warsaw"});await r.offers.create({source:"other",url:"https://x.test/2",title:"React Dev",company:"Acme",location:"Warsaw"});await r.offers.create({source:"manual",url:"bad",title:null});const out=await service(r.offers).reindex();expect(out.duplicatesMerged).toBe(1);expect(out.invalidRecordsFound).toBe(1);expect((await r.offers.all()).some(x=>x.searchableText.includes("react"))).toBe(true);}));
 it("previews and executes cleanup while protecting saved/applied records",async()=>withDb(async(_ctx,r)=>{const old=new Date(Date.now()-40*86400000).toISOString();await r.offers.create({source:"manual",url:"https://x.test/saved",title:"Saved",company:"A",status:"saved",lastSeenAt:old});const stale=await r.offers.create({source:"manual",url:"https://x.test/stale",title:"Stale",company:"B",lastSeenAt:old});const s=service(r.offers);const opts={markExpiredAfterDays:30,deleteInvalidAfterDays:90,preserveSavedApplied:true,preservePinned:true};const preview=await s.cleanupPreview(opts);expect(preview.protected).toBe(1);await expect(s.cleanupExecute({...opts,mode:"delete"})).rejects.toThrow(/confirmation/);const done=await s.cleanupExecute({...opts,mode:"mark"});expect(done.protected).toBe(1);expect((await r.offers.getById(stale.id))?.status).toBe("expired");}));
 it("creates deterministic fingerprints",()=>expect(createOfferFingerprint("React Dev","Acme","Warsaw")).toBe(createOfferFingerprint(" react  dev ","ACME","Warsaw")));
});
